import './globals.css'
import { Font } from '@/lib/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Font.className}>{children}</body>
    </html>
  )
}
